/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package gg.stardust.coresdk.models

import gg.stardust.coresdk.models.SDGameGetResponseFeesInner

import com.squareup.moshi.Json
import java.io.Serializable

/**
 * This is the data output json model
 *
 * @param id Game ID Number (unsigned 32 bit integer)
 * @param ownerId Game Owner ID
 * @param name Game name
 * @param desc Game description
 * @param image Game image
 * @param bucketName Game bucket name
 * @param news Game news
 * @param fees 
 * @param props Game properties
 * @param testMode If on test mode features are enabled. Currently in development.
 */


data class SDGameGetResponse (

    /* Game ID Number (unsigned 32 bit integer) */
    @Json(name = "id")
    val id: kotlin.Int,

    /* Game Owner ID */
    @Json(name = "ownerId")
    val ownerId: kotlin.String,

    /* Game name */
    @Json(name = "name")
    val name: kotlin.String,

    /* Game description */
    @Json(name = "desc")
    val desc: kotlin.String,

    /* Game image */
    @Json(name = "image")
    val image: kotlin.String,

    /* Game bucket name */
    @Json(name = "bucketName")
    val bucketName: kotlin.String,

    /* Game news */
    @Json(name = "news")
    val news: kotlin.String? = null,

    @Json(name = "fees")
    val fees: kotlin.collections.List<SDGameGetResponseFeesInner>? = null,

    /* Game properties */
    @Json(name = "props")
    val props: kotlin.Any? = null,

    /* If on test mode features are enabled. Currently in development. */
    @Json(name = "testMode")
    val testMode: kotlin.Boolean? = null

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

