/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package gg.stardust.coresdk.models


import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 *
 * @param feePercentage The integer value of feePercentage. 
 * @param feeType The type of fee
 */


data class SDGameGetResponseFeesInner (

    /* The integer value of feePercentage.  */
    @Json(name = "feePercentage")
    val feePercentage: kotlin.Int? = null,

    /* The type of fee */
    @Json(name = "feeType")
    val feeType: kotlin.String? = null

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

