/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package gg.stardust.coresdk.models


import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 *
 * @param description The games description
 * @param news The games news
 * @param props Game properties
 * @param testMode Test mode will enable any test mode features. Currently in development.
 */


data class SDGameMutateRequest (

    /* The games description */
    @Json(name = "description")
    val description: kotlin.String? = null,

    /* The games news */
    @Json(name = "news")
    val news: kotlin.String? = null,

    /* Game properties */
    @Json(name = "props")
    val props: kotlin.Any? = null,

    /* Test mode will enable any test mode features. Currently in development. */
    @Json(name = "testMode")
    val testMode: kotlin.Boolean? = null

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

