/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package gg.stardust.coresdk.models


import com.squareup.moshi.Json
import java.io.Serializable

/**
 * Data model for the /health response
 *
 * @param status Connect to AWS subsystems worked properly, i.e. OK
 */


data class SDHealthResponse (

    /* Connect to AWS subsystems worked properly, i.e. OK */
    @Json(name = "status")
    val status: kotlin.String

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

