/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package gg.stardust.coresdk.models


import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 *
 * @param orderId Order ID Number (unsigned 32 bit integer)
 * @param acceptedBy The player who accepted the order
 */


data class SDOrderBuyRequest (

    /* Order ID Number (unsigned 32 bit integer) */
    @Json(name = "orderId")
    val orderId: kotlin.Int,

    /* The player who accepted the order */
    @Json(name = "acceptedBy")
    val acceptedBy: kotlin.String

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

