/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package gg.stardust.coresdk.models


import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 *
 * @param tokenId Token ID Number (unsigned 32 bit integer)
 * @param amount Token ID Number (unsigned 32 bit integer)
 */


data class SDOrderGetAllResponseTokensRequestedInner (

    /* Token ID Number (unsigned 32 bit integer) */
    @Json(name = "tokenId")
    val tokenId: kotlin.Int,

    /* Token ID Number (unsigned 32 bit integer) */
    @Json(name = "amount")
    val amount: kotlin.Int

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

