/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package gg.stardust.coresdk.models


import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 *
 * @param gameId Game ID Number (unsigned 32 bit integer)
 * @param orderId Order ID Number (unsigned 32 bit integer)
 * @param fromPlayerId The Player's id, can be found with Player/getId(s). Also returned from player/create (ex. CzySggxVQz51jciGRFDY7d5BER2fav6TNEnPGjusPJPd)
 */


data class SDOrderCancelRequest (

    /* Game ID Number (unsigned 32 bit integer) */
    @Json(name = "gameId")
    val gameId: kotlin.Int,

    /* Order ID Number (unsigned 32 bit integer) */
    @Json(name = "orderId")
    val orderId: kotlin.Int,

    /* The Player's id, can be found with Player/getId(s). Also returned from player/create (ex. CzySggxVQz51jciGRFDY7d5BER2fav6TNEnPGjusPJPd) */
    @Json(name = "fromPlayerId")
    val fromPlayerId: kotlin.String? = null

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

