/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package gg.stardust.coresdk.models


import com.squareup.moshi.Json
import java.io.Serializable

/**
 * This is the data output json model
 *
 * @param playerId Player ID in the form of a UUID
 * @param uniqueId Player ID in the form of a the game owner's internal playerId, i.e. email address
 * @param lastSeen Date and time the player was 'last seen' actively participating in the game
 * @param image URL of image cached by Stardust
 */


data class SDPlayerGetResponse (

    /* Player ID in the form of a UUID */
    @Json(name = "playerId")
    val playerId: kotlin.String,

    /* Player ID in the form of a the game owner's internal playerId, i.e. email address */
    @Json(name = "uniqueId")
    val uniqueId: kotlin.String,

    /* Date and time the player was 'last seen' actively participating in the game */
    @Json(name = "lastSeen")
    val lastSeen: kotlin.String? = null,

    /* URL of image cached by Stardust */
    @Json(name = "image")
    val image: kotlin.String? = null

) : kotlin.collections.HashMap<String, kotlin.String>(), Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

