/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package gg.stardust.coresdk.models


import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 *
 * @param type Your provider JWT name
 * @param idToken idToken of the user session
 * @param accessToken Access token of the user session
 */


data class SDPlayerCreateJWTObject (

    /* Your provider JWT name */
    @Json(name = "type")
    val type: kotlin.String,

    /* idToken of the user session */
    @Json(name = "idToken")
    val idToken: kotlin.String? = null,

    /* Access token of the user session */
    @Json(name = "accessToken")
    val accessToken: kotlin.String? = null

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

