/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package gg.stardust.coresdk.models


import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 *
 * @param playerId Can be found with Player/getId(s).
 * @param props Specifies which properties you want to change (ex. {prop1: 5, prop2: 6, prop3: 7})
 */


data class SDPlayerMutateRequest (

    /* Can be found with Player/getId(s). */
    @Json(name = "playerId")
    val playerId: kotlin.String,

    /* Specifies which properties you want to change (ex. {prop1: 5, prop2: 6, prop3: 7}) */
    @Json(name = "props")
    val props: kotlin.Any

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

