/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package gg.stardust.coresdk.models

import gg.stardust.coresdk.models.SDPlayerWalletGetResponseWalletInner

import com.squareup.moshi.Json
import java.io.Serializable

/**
 * This is the data output json model
 *
 * @param wallet An array of player wallets on the blockchain
 */


data class SDPlayerWalletGetResponse (

    /* An array of player wallets on the blockchain */
    @Json(name = "wallet")
    val wallet: kotlin.collections.List<SDPlayerWalletGetResponseWalletInner>

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

