/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package gg.stardust.coresdk.models


import com.squareup.moshi.Json
import java.io.Serializable

/**
 * This is the data output json model, i.e. {\"uniqueId\": \"playerId\"} 
 *
 * @param playerId Player ID in the form of a UUID
 * @param uniqueId Player ID in the form of a the game player's internal playerId, i.e. email address, uuid
 */


data class SDPlayerGetIdsResponse (

    /* Player ID in the form of a UUID */
    @Json(name = "playerId")
    val playerId: kotlin.String,

    /* Player ID in the form of a the game player's internal playerId, i.e. email address, uuid */
    @Json(name = "uniqueId")
    val uniqueId: kotlin.String

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

