/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package gg.stardust.coresdk.models

import gg.stardust.coresdk.models.SDPlayerWalletGetResponseWalletInnerMoniesInner

import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 *
 * @param blockchain The name of the blockchain
 * @param address The players blockchain Address
 * @param monies An array of the players balances on a given blockchain
 */


data class SDPlayerWalletGetResponseWalletInner (

    /* The name of the blockchain */
    @Json(name = "blockchain")
    val blockchain: kotlin.String,

    /* The players blockchain Address */
    @Json(name = "address")
    val address: kotlin.String,

    /* An array of the players balances on a given blockchain */
    @Json(name = "monies")
    val monies: kotlin.collections.List<SDPlayerWalletGetResponseWalletInnerMoniesInner>? = null

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

