/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package gg.stardust.coresdk.models

import gg.stardust.coresdk.models.SDTemplateGetTokensResponsePlayer
import gg.stardust.coresdk.models.SDTemplateGetTokensResponseToken

import com.squareup.moshi.Json
import java.io.Serializable

/**
 * Token data
 *
 * @param token 
 * @param player 
 */


data class SDTemplateGetTokensResponse (

    @Json(name = "token")
    val token: SDTemplateGetTokensResponseToken,

    @Json(name = "player")
    val player: SDTemplateGetTokensResponsePlayer

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

