/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package gg.stardust.coresdk.models


import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 *
 * @param templateId This is the templateId returned from template/create (ex. 5)
 * @param props Specifies which properties you want to change (ex. {prop1: 5, prop2: 6, prop3: 7})
 * @param publicContractMetadata Returned to marketplaces as contract metadata
 * @param publicTokenMetadata Inherited by tokens, and returned to marketplaces as token metadata
 */


data class SDTemplateMutateRequest (

    /* This is the templateId returned from template/create (ex. 5) */
    @Json(name = "templateId")
    val templateId: kotlin.Int,

    /* Specifies which properties you want to change (ex. {prop1: 5, prop2: 6, prop3: 7}) */
    @Json(name = "props")
    val props: kotlin.Any? = null,

    /* Returned to marketplaces as contract metadata */
    @Json(name = "publicContractMetadata")
    val publicContractMetadata: kotlin.Any? = null,

    /* Inherited by tokens, and returned to marketplaces as token metadata */
    @Json(name = "publicTokenMetadata")
    val publicTokenMetadata: kotlin.Any? = null

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

