/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package gg.stardust.coresdk.models


import com.squareup.moshi.Json
import java.io.Serializable

/**
 * Internal metadata
 *
 * @param mutable Specifies which properties you want to add (ex. {prop1: 5, prop2: 6, prop3: 7})
 * @param immutable Specifies which properties you want to add (ex. {prop1: 5, prop2: 6, prop3: 7})
 */


data class SDTokenMintBulkTokenObjectProps (

    /* Specifies which properties you want to add (ex. {prop1: 5, prop2: 6, prop3: 7}) */
    @Json(name = "mutable")
    val mutable: kotlin.Any,

    /* Specifies which properties you want to add (ex. {prop1: 5, prop2: 6, prop3: 7}) */
    @Json(name = "immutable")
    val immutable: kotlin.Any? = null

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

