/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package gg.stardust.coresdk.models

import gg.stardust.coresdk.models.SDTokenMintBulkTokenObjectProps

import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 *
 * @param templateId Specifies which Template you are creating an instance of (ex. 3)
 * @param amount u64 Number as String, min: 0, max: 9223372036854775807 (ex. \"6\")
 * @param props 
 * @param publicMetadata Returned to marketplaces as token metadata
 */


data class SDTokenMintBulkTokenObject (

    /* Specifies which Template you are creating an instance of (ex. 3) */
    @Json(name = "templateId")
    val templateId: kotlin.Int,

    /* u64 Number as String, min: 0, max: 9223372036854775807 (ex. \"6\") */
    @Json(name = "amount")
    val amount: kotlin.String,

    @Json(name = "props")
    val props: SDTokenMintBulkTokenObjectProps? = null,

    /* Returned to marketplaces as token metadata */
    @Json(name = "publicMetadata")
    val publicMetadata: kotlin.Any? = null

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

