/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package gg.stardust.coresdk.models

import gg.stardust.coresdk.models.SDTokenBurnRequestTokenObjectsInner

import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 *
 * @param playerId The Player's id, can be found with Player/getId(s). (ex. CzySggxVQz51jciGRFDY7d5BER2fav6TNEnPGjusPJPd)
 * @param tokenObjects An an array of objects to burn (ex. [{tokenId: 5, amount: \"6\"}])
 */


data class SDTokenBurnRequest (

    /* The Player's id, can be found with Player/getId(s). (ex. CzySggxVQz51jciGRFDY7d5BER2fav6TNEnPGjusPJPd) */
    @Json(name = "playerId")
    val playerId: kotlin.String,

    /* An an array of objects to burn (ex. [{tokenId: 5, amount: \"6\"}]) */
    @Json(name = "tokenObjects")
    val tokenObjects: kotlin.collections.List<SDTokenBurnRequestTokenObjectsInner>

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

