/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package gg.stardust.coresdk.models

import gg.stardust.coresdk.models.SDTokenMintBulkTokenObject

import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 *
 * @param playerId The player ID that was returned from player/create
 * @param tokenObjects array of Token objects
 */


data class SDTokenMintBulkRequest (

    /* The player ID that was returned from player/create */
    @Json(name = "playerId")
    val playerId: kotlin.String,

    /* array of Token objects */
    @Json(name = "tokenObjects")
    val tokenObjects: kotlin.collections.List<SDTokenMintBulkTokenObject>

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

