/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package gg.stardust.coresdk.models

import gg.stardust.coresdk.models.SDTokenBurnRequestTokenObjectsInner

import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 *
 * @param fromPlayerId The Player's id, can be found with Player/getId(s). (ex. CzySggxVQz51jciGRFDY7d5BER2fav6TNEnPGjusPJPd)
 * @param toPlayerId The Player's id, can be found with Player/getId(s). (ex. 53ywNSVp46QpiA6S86DLLfeKVfjcSAFxHR2L9j8tnte2)
 * @param tokenObjects An array of objects of which tokens to transfer (ex. [{tokenId: 5, amount: \"3\"}])
 */


data class SDTokenTransferRequest (

    /* The Player's id, can be found with Player/getId(s). (ex. CzySggxVQz51jciGRFDY7d5BER2fav6TNEnPGjusPJPd) */
    @Json(name = "fromPlayerId")
    val fromPlayerId: kotlin.String,

    /* The Player's id, can be found with Player/getId(s). (ex. 53ywNSVp46QpiA6S86DLLfeKVfjcSAFxHR2L9j8tnte2) */
    @Json(name = "toPlayerId")
    val toPlayerId: kotlin.String,

    /* An array of objects of which tokens to transfer (ex. [{tokenId: 5, amount: \"3\"}]) */
    @Json(name = "tokenObjects")
    val tokenObjects: kotlin.collections.List<SDTokenBurnRequestTokenObjectsInner>

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

