/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package gg.stardust.coresdk.models

import gg.stardust.coresdk.models.SDTemplateGetTokensResponseTokenProps

import com.squareup.moshi.Json
import java.io.Serializable

/**
 * token data
 *
 * @param gameId Game ID Number (unsigned 32 bit integer)
 * @param templateId Template ID Number (unsigned 32 bit integer)
 * @param id The ID of the token created
 * @param flags 
 * @param props 
 * @param name The name of the template
 * @param owner Game Owner's Public Key
 * @param publicMetadata Returned to marketplaces as token metadata
 */


data class SDTokenGetResponse (

    /* Game ID Number (unsigned 32 bit integer) */
    @Json(name = "gameId")
    val gameId: kotlin.Int,

    /* Template ID Number (unsigned 32 bit integer) */
    @Json(name = "templateId")
    val templateId: kotlin.Int,

    /* The ID of the token created */
    @Json(name = "id")
    val id: kotlin.Int,

    @Json(name = "flags")
    val flags: kotlin.Int,

    @Json(name = "props")
    val props: SDTemplateGetTokensResponseTokenProps,

    /* The name of the template */
    @Json(name = "name")
    val name: kotlin.String? = null,

    /* Game Owner's Public Key */
    @Json(name = "owner")
    val owner: kotlin.String? = null,

    /* Returned to marketplaces as token metadata */
    @Json(name = "publicMetadata")
    val publicMetadata: kotlin.Any? = null

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

