/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package gg.stardust.coresdk.models

import gg.stardust.coresdk.models.SDTokenWithdrawObject

import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 *
 * @param address External (non-custodial) blockchain wallet address
 * @param playerId The Player's id, can be found with Player/getId(s) in uuid format. Also returned from player/create (ex. XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX)
 * @param tokenObjects Array of Token objects
 */


data class SDTokenWithdrawRequest (

    /* External (non-custodial) blockchain wallet address */
    @Json(name = "address")
    val address: kotlin.String,

    /* The Player's id, can be found with Player/getId(s) in uuid format. Also returned from player/create (ex. XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX) */
    @Json(name = "playerId")
    val playerId: kotlin.String,

    /* Array of Token objects */
    @Json(name = "tokenObjects")
    val tokenObjects: kotlin.collections.List<SDTokenWithdrawObject>

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

